version: 2
jobs:
   build:
     docker:
       - image: circleci/golang:1.9.3-stretch
     working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
     steps:
       - checkout
       - run: go build .
